services:
  transactiondb:
    image: postgres
    environment:
      - POSTGRES_DB=transactiondb
      - POSTGRES_USER=transactionuser
      - POSTGRES_PASSWORD=transactionpassword
    command: -p 5433
    ports:
      - 5433:5433
  transactionservice:
    build: ./transaction_service
    image: transactionservice
    restart: always
    command: 
      - /app/transaction_service/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=transactiondb
      - POSTGRES_USER=transactionuser
      - POSTGRES_PASSWORD=transactionpassword
      - POSTGRES_PORT=5433
    depends_on:
      - transactiondb
  accountdb:
    image: postgres
    environment:
      - POSTGRES_DB=accountdb
      - POSTGRES_USER=accountuser
      - POSTGRES_PASSWORD=accountpassword
    ports:
      - 5432:5432
  accountservice:
    build: ./account_service
    image: accountservice
    restart: always
    command: 
      - /app/account_service/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=accountdb
      - POSTGRES_USER=accountuser
      - POSTGRES_PASSWORD=accountpassword
      - POSTGRES_PORT=5432
    depends_on:
      - accountdb