FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app/account_service
COPY requirements.txt /app/account_service
RUN pip install -r requirements.txt
COPY . /app/account_service