services:
  account_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=accountdb
      - POSTGRES_USER=accountuser
      - POSTGRES_PASSWORD=accountpassword
    ports:
      - 54320:5432
  account_service:
    build: .
    image: accountservice
    command: 
      - /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=accountdb
      - POSTGRES_USER=accountuser
      - POSTGRES_PASSWORD=accountpassword
    depends_on:
      - account_db