FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app/transaction_service
COPY requirements.txt /app/transaction_service
RUN pip install -r requirements.txt
COPY . /app/transaction_service
CMD ["-p", "5433"]